# Generated by Django 5.2.8 on 2025-11-13 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id_corredor', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_c',
            fields=[
                ('id_detalle', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('tipo_dato', models.CharField(max_length=10)),
                ('valor_monto', models.FloatField(null=True)),
                ('valor_factor', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id_emisor', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('año_tributario', models.IntegerField(null=True)),
                ('fecha_creacion_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NuamApp.cliente')),
                ('id_emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NuamApp.emisor')),
            ],
        ),
    ]
