# Generated by Django 6.0 on 2025-12-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NuamApp', '0002_cliente_corredor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
